language: php
addons:
  sonarcloud:
    organization: "ldap-account-manager"
php:
  - '7.3'

before_install:
  - nvm install 6.10

install
  - npm install

cache:
  directories:
    - '$HOME/.sonar/cache'

script:
  - phpunit
  - ls -l code-coverage/*
  - sonar-scanner
  - pip install --user codespell
  - cd lam
  - ./codespell.sh
