#!/bin/bash
# $Id$
#
# Copyright (C) 2004  Roland Gruber
# This code is part of LDAP Account Manager (http://www.sourceforge.net/projects/lam)

# This script is run after make_po to merge the existing Japanese translations to messages.po

msgmerge -v ../locale/ja_JP/LC_MESSAGES/messages.po messages.po -o messages.po
