#!/bin/bash

. /usr/share/debconf/confmodule
db_version 2.0 || [ 0 -lt 30 ]

db_input medium "ldap-account-manager/config-webserver" || true
db_go
db_input low "ldap-account-manager/alias" || true
db_go
db_input low "ldap-account-manager/passwd" || true
db_go
db_input medium "ldap-account-manager/restart-webserver" || true
db_go

#DEBHELPER#

exit 0
