#!/bin/bash

set -e
outFile=templates/lib/100_lam.${SOURCE_DATE_EPOCH}.min.js
if [ ! -e $outFile ]; then
  mkdir debian/build-min/
	files=`ls templates/lib/*.js`
	jsFiles=""
	for file in $files; do
		jsFiles="$jsFiles $file"
	done
	terser $jsFiles -o $outFile
  for file in $files; do
    mv $file debian/build-min/
  done
	# add final new line to supress Debian warnings
	echo "" >> $outFile

  files=`ls style/*.css`
  outFile=style/100_lam.${SOURCE_DATE_EPOCH}.min.css
	cat $files | cleancss -o ${outFile}
  for file in $files; do
    mv $file debian/build-min/
  done
	# add final new line to supress Debian warnings
	echo "" >> $outFile
fi
