#!/bin/bash

set -e

files=`ls templates/lib/*.js`
for file in $files; do
	closure-compiler --charset UTF-8 --js file --js_output_file ${file}-MIN
	rm $file
	mv ${file}-MIN $file
	# add final new line to supress Debian warnings
	echo "" >> $file
done

files=`ls style/*.css`
for file in $files; do
	cleancss -o ${file}-MIN $file file
	rm $file
	mv ${file}-MIN $file
	# add final new line to supress Debian warnings
	echo "" >> $file
done

