#!/bin/bash

set -e

if [ "$1" = "upgrade" ]; then
	exit 0
fi

if [ -f /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_version 2.0 || [ $? -lt 30 ]

  rm -f /usr/share/ldap-account-manager/sess
  rm -f /usr/share/ldap-account-manager/tmp
  rm -f /usr/share/ldap-account-manager/config

  set +e
	db_get "ldap-account-manager/config-webserver"
	if [ $? -eq 0 ]; then
		set -e
		webservers="$RET"
		restart=""
		for server in $webservers; do
				server=${server%,}
				case "$server" in
						apache2)
								set +e
								a2query -q -c ldap-account-manager && a2disconf -q ldap-account-manager
								set -e
								rm -f /etc/$server/conf-available/ldap-account-manager.conf
								test -x /usr/sbin/$server || continue
								restart="$restart $server"
								;;
				esac
		done
	fi

	set +e
	db_get "ldap-account-manager/restart-webserver"
	if [ $? -eq 0 ] && [ "$RET" = "true" ]; then
		set -e
		for server in $restart; do
				server=${server%,}
				if [ `which invoke-rc.d` ]; then
					invoke-rc.d $server reload
				fi
		done
	fi

	# 3rd party libs
	phpThirdPartyLibs='phpseclib tcpdf Monolog Psr'
	for phpThirdPartyLib in $phpThirdPartyLibs; do
		if [ -L /usr/share/ldap-account-manager/lib/3rdParty/${phpThirdPartyLib} ] ; then
			rm /usr/share/ldap-account-manager/lib/3rdParty/${phpThirdPartyLib}
		fi
	done


	set -e
	if [ "$1" = "purge" ]; then
		rm -r -f /usr/share/ldap-account-manager
		rm -r -f /var/lib/ldap-account-manager
		db_purge
	fi

	#DEBHELPER#

	db_stop

fi

exit 0
