#!/bin/bash

set -e

. /usr/share/debconf/confmodule
db_version 2.0 || [ $? -lt 30 ]

cd /usr/share/ldap-account-manager/config-samples/profiles
files=`ls -a default.*`
for file in $files; do
	if [ ! -f /var/lib/ldap-account-manager/config/templates/profiles/$file ]; then
		cp $file /var/lib/ldap-account-manager/config/templates/profiles/$file
	fi
done
cd /usr/share/ldap-account-manager/config-samples/pdf
files=`ls -a default.*`
for file in $files; do
	if [ ! -f /var/lib/ldap-account-manager/config/templates/pdf/$file ]; then
		cp $file /var/lib/ldap-account-manager/config/templates/pdf/$file
	fi
done
cd /usr/share/ldap-account-manager/config-samples/pdf/logos
files=`ls -a *.jpg`
for file in $files; do
	cp $file /var/lib/ldap-account-manager/config/templates/pdf/logos/$file
done
cd /usr/share/ldap-account-manager/config-samples/selfService
files=`ls -a default.*`
for file in $files; do
	if [ ! -f /var/lib/ldap-account-manager/config/selfService/$file ]; then
		cp $file /var/lib/ldap-account-manager/config/selfService/$file
	fi
done
if [ ! -h /usr/share/ldap-account-manager/lib/fpdf.php ]; then\
  ln -s /usr/share/fpdf/fpdf.php /usr/share/ldap-account-manager/lib/fpdf.php; fi
if [ ! -h /usr/share/ldap-account-manager/config ]; then\
  ln -s /var/lib/ldap-account-manager/config /usr/share/ldap-account-manager/config; fi
if [ ! -h /usr/share/ldap-account-manager/sess ]; then\
  ln -s /var/lib/ldap-account-manager/sess /usr/share/ldap-account-manager/sess; fi
if [ ! -h /usr/share/ldap-account-manager/tmp ]; then\
  ln -s /var/lib/ldap-account-manager/tmp /usr/share/ldap-account-manager/tmp; fi
chown www-data /etc/ldap-account-manager/config.cfg
chmod 600 /etc/ldap-account-manager/config.cfg
chown www-data /var/lib/ldap-account-manager/sess
chmod 700 /var/lib/ldap-account-manager/sess
chown www-data /var/lib/ldap-account-manager/tmp
chown www-data /var/lib/ldap-account-manager/tmp/internal
chmod 700 /var/lib/ldap-account-manager/tmp
chown -R www-data /var/lib/ldap-account-manager/config
chmod 700 /var/lib/ldap-account-manager/config
if [ ! -f /var/lib/ldap-account-manager/config/lam.conf ]; \
   then cp /var/lib/ldap-account-manager/config/lam.conf_sample /var/lib/ldap-account-manager/config/lam.conf; \
	chown www-data /var/lib/ldap-account-manager/config/lam.conf; fi
chmod 600 /var/lib/ldap-account-manager/config/*.conf
if [ "$1" = "configure" ]; then
    db_get "ldap-account-manager/alias"
    alias="$RET"
	 perl -pi -e "s/Alias \/.* \/usr\/share\/ldap-account-manager/Alias \/$alias \/usr\/share\/ldap-account-manager/g"\
        /etc/ldap-account-manager/apache.conf
    db_get "ldap-account-manager/config-webserver"
    webservers="$RET"
    restart=""
   for server in $webservers; do
       server=${server%,}
       test -x /usr/sbin/$server || continue
       case "$server" in
           apache2)
               if [ -d /etc/$server/mods-enabled ]; then
                   if [ ! -f /etc/$server/mods-enabled/actions.load -a ! -h /etc/$server/mods-enabled/actions.load ]; then
                       ln -s /etc/$server/mods-available/actions.load /etc/$server/mods-enabled/actions.load
                   fi
                   if [ -f /etc/apache2/mods-available/php5.load ]; then
                       if [ ! -f /etc/$server/mods-enabled/php5.load -a ! -h /etc/$server/mods-enabled/php5.load ]; then
                           ln -s /etc/$server/mods-available/php5.load /etc/$server/mods-enabled/php5.load
                       fi
                   fi
                   if [ -f /etc/apache2/mods-available/php5.conf ]; then
                       if [ ! -f /etc/$server/mods-enabled/php5.conf -a ! -h /etc/$server/mods-enabled/php5.conf ]; then
                           ln -s /etc/$server/mods-available/php5.conf /etc/$server/mods-enabled/php5.conf
                       fi
                   fi
               fi
               if [ -d /etc/$server/conf.d -a ! -e /etc/$server/conf.d/ldap-account-manager ]; then
                   ln -s /etc/ldap-account-manager/apache.conf /etc/$server/conf.d/ldap-account-manager
                   restart="$restart $server"
               fi
               if [ -d /etc/$server/conf-available ]; then
                   if [ ! -e /etc/$server/conf-available/ldap-account-manager ]; then
                       ln -s /etc/ldap-account-manager/apache.conf /etc/$server/conf-available/ldap-account-manager
                   fi
                   if [ ! -e /etc/$server/conf-enabled/ldap-account-manager ]; then
                       ln -s ../conf-available/ldap-account-manager /etc/$server/conf-enabled/ldap-account-manager
                   fi
                   restart="$restart $server"
               fi
               ;;
       esac
   done
   db_get "ldap-account-manager/restart-webserver"
   if [ "$RET" = "true" ]; then
       for server in $restart; do
           server=${server%,}
           if [ -x /usr/sbin/invoke-rc.d ]; then
               invoke-rc.d $server reload
           else
               /etc/init.d/$server reload
           fi
       done
   fi
	fi

#DEBHELPER#

db_stop

exit 0
