#!/bin/bash
# $Id$
#
# Copyright (C) 2003  Roland Gruber
# This code is part of LDAP Account Manager (http://www.sourceforge.net/projects/lam)

# This script generates a messages.mo file from the translated messages.po file.

rm -f messages.mo
msgfmt -v messages.po -o messages.mo
