#!/bin/bash
# $Id$
#
# Copyright (C) 2008  Roland Gruber
# This code is part of LDAP Account Manager (http://www.sourceforge.net/projects/lam)

# This script is run after make_po to merge the existing Polish translations to messages.po

./make_po
msgmerge -v ../locale/pl_PL/LC_MESSAGES/messages.po messages.po -o messages.po