#!/bin/bash
./make_po_ca
tar -czf messages.po_ca.tar.gz messages.po  
./make_po_es
tar -czf messages.po_es.tar.gz messages.po  
./make_po_fr
tar -czf messages.po_fr.tar.gz messages.po  
./make_po_hu
tar -czf messages.po_hu.tar.gz messages.po  
./make_po_it
tar -czf messages.po_it.tar.gz messages.po  
./make_po_jp
tar -czf messages.po_jp.tar.gz messages.po  

