#!/bin/bash
# $Id$
#
# Copyright (C) 2003 - 2017  Roland Gruber
# This code is part of LDAP Account Manager (http://www.ldap-account-manager.org/)

# This script generates a messages.mo file from the translated messages.po file.

rm -f messages.mo
chmod -x messages.po
msgfmt -v -c --statistics messages.po -o messages.mo
