#!/bin/bash
#
# Copyright (C) 2025  Roland Gruber
# This code is part of LDAP Account Manager (http://www.ldap-account-manager.org/)

# This script is run after make_po to merge the existing Greek translations to messages.po

./make_po
msgmerge -v ../locale/el_GR/LC_MESSAGES/messages.po messages.po -o messages.po
