#!/bin/bash
# $Id$
#
# Copyright (C) 2004 - 2006  Roland Gruber
# This code is part of LDAP Account Manager (http://www.sourceforge.net/projects/lam)

# This script is run to create archives of all messages.po files.

#!/bin/bash
echo "Generating Catalan translation template"
./make_po_ca
tar -czf messages.po_ca.tar.gz messages.po  
echo " "
echo "Generating Chinese translation template"
./make_po_zh
tar -czf messages.po_zh.tar.gz messages.po  
echo " "
echo "Generating Dutch translation template"
./make_po_nl
tar -czf messages.po_nl.tar.gz messages.po  
echo " "
echo "Generating Spanish translation template"
./make_po_es
tar -czf messages.po_es.tar.gz messages.po  
echo " "
echo "Generating French translation template"
./make_po_fr
tar -czf messages.po_fr.tar.gz messages.po  
echo " "
echo "Generating Hungarian translation template"
./make_po_hu
tar -czf messages.po_hu.tar.gz messages.po  
echo " "
echo "Generating Italian translation template"
./make_po_it
tar -czf messages.po_it.tar.gz messages.po  
echo " "
echo "Generating Japanese translation template"
./make_po_jp
tar -czf messages.po_jp.tar.gz messages.po  
echo " "
echo "Generating Russian translation template"
./make_po_ru
tar -czf messages.po_ru.tar.gz messages.po  

rm messages.po
