#!/bin/bash
# $Id$
#
# Copyright (C) 2003 - 2006  Roland Gruber
# This code is part of LDAP Account Manager (http://www.ldap-account-manager.org/)

# This script is run after make_po to merge the existing Catalan translations to messages.po

./make_po
msgmerge -v ../locale/ca_ES/LC_MESSAGES/messages.po messages.po -o messages.po