#!/bin/bash
#
# Copyright (C) 2013 - 2026  Roland Gruber
# This code is part of LDAP Account Manager (http://www.ldap-account-manager.org/)

# This script is run after make_po to merge the existing Ukrainian translations to messages.po

./make_po
msgmerge -v ../locale/uk_UA/LC_MESSAGES/messages.po messages.po -o messages.po