#!/bin/bash
# $Id$
#
# Copyright (C) 2006  Roland Gruber
# This code is part of LDAP Account Manager (http://www.ldap-account-manager.org/)

# This script is run after make_po to merge the existing Russian translations to messages.po

./make_po
msgmerge -v ../locale/ru_RU/LC_MESSAGES/messages.po messages.po -o messages.po
