#!/bin/bash
# $Id$
#
# Copyright (C) 2003  Roland Gruber
# This code is part of LDAP Account Manager (http://www.sourceforge.net/projects/lam)

# This script generates a messages.po file for translation from all .inc and .php files.

rm -f messages.po
touch messages.po
find ../ -name *.php -exec xgettext --keyword=_ -L PHP -j -s {} \;
find ../ -name *.inc -exec xgettext --keyword=_ -L PHP -j -s {} \;
