#!/bin/bash
# $Id$
#
# Copyright (C) 2004 - 2006  Roland Gruber
# This code is part of LDAP Account Manager (http://www.ldap-account-manager.org/)

# This script is run to update the existing Spanish translations in messages.po

./make_po
msgmerge -v ../locale/es_ES/LC_MESSAGES/messages.po messages.po -o messages.po
