name: "OWASP dep-scan"

on:
  schedule:
    - cron: '0 3 * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit

    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Install dep-scan
      run: pipx install owasp-depscan

    - name: dep-scan-full
      run: ~/.local/bin/depscan --bom lam/sbom.json

    - name: dep-scan
      run: ~/.local/bin/depscan --bom lam/sbom.json 2>&1 | grep "No oss vulnerabilities detected"
