name: "OWASP dep-scan"

on:
  schedule:
    - cron: '0 3 * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
      with:
        egress-policy: audit

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Install dep-scan
      run: pipx install owasp-depscan

    - name: dep-scan-full
      run: ~/.local/bin/depscan --bom lam/sbom.json

    - name: dep-scan
      run: ~/.local/bin/depscan --bom lam/sbom.json 2>&1 | grep "No oss vulnerabilities detected"
