name: "Quality"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
      with:
        egress-policy: audit

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
      with:
        php-version: '8.2'
        extensions: ldap, xdebug, gd, json, xml, curl, zip, mbstring, imagick, pdo_sqlite

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: vendor
        key: ${{ runner.os }}-quality-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-quality-

    - name: PHP Version
      run: php --version

    - name: Install dependencies
      run: composer install --no-progress

    - name: Install CodeSpell
      run: pipx install codespell

    - name: CodeSpell
      run: ./codespell.sh

    - name: PHPStan Version
      run: ./vendor/bin/phpstan -V

    - name: PHPStan
      run: ./vendor/bin/phpstan

    - name: Rector
      run: ./vendor/bin/rector process --dry-run
