name: "Quality"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231 # v2
      with:
        php-version: '8.1'
        extensions: ldap, xdebug, gd, json, xml, curl, zip, mbstring

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3.3.3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: PHP Version
      run: php --version

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Install CodeSpell
      run: pip install --user codespell

    - name: CodeSpell
      run: ./codespell.sh

    - name: PHPStan Version
      run: ./vendor/bin/phpstan -V

    - name: PHPStan
      run: ./vendor/bin/phpstan --xdebug

    - name: Rector
      run: ./vendor/bin/rector process --dry-run
