name: "Quality"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
      with:
        egress-policy: audit

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # v2
      with:
        php-version: '8.2'
        extensions: ldap, xdebug, gd, json, xml, curl, zip, mbstring, imagick, pdo_sqlite

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      with:
        path: vendor
        key: ${{ runner.os }}-quality-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-quality-

    - name: PHP Version
      run: php --version

    - name: Install dependencies
      run: composer install --no-progress

    - name: Install CodeSpell
      run: pipx install codespell

    - name: CodeSpell
      run: ./codespell.sh

    - name: PHPStan Version
      run: ./vendor/bin/phpstan -V

    - name: PHPStan
      run: ./vendor/bin/phpstan

    - name: Rector
      run: ./vendor/bin/rector process --dry-run
